# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SoYee
tagline:          'SoYee'
description:      'Love.<br>And Being Loved.'
url:              http://princeliebe.github.io/

author:
  name:           'SoYee'
  url:            http://princeliebe.github.io/

paginate:         2
emailme:          mailto:princeliebe@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/princeliebe/princeliebe.github.io/

tags:

github_username:  princeliebe
linkedin_username: junhua-yee-773295107


