# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            princeliebe
tagline:          'princelieb'
description:      'Reality augmented.<br>My personal blog.'
url:              http://princeliebe.github.io/

author:
  name:           'princeliebe'
  url:            http://princeliebe.github.io/

paginate:         2
emailme:          mailto:princeliebe@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/princeliebe/princeliebe.github.io/

tags:

github_username:  princeliebe
facebook_username: So Yee
linkedin_username: Junhua Yi


